### ISSUE TITLE
Better DNS support in later version of Alpine Linux

### ISSUE THREAD

**Issue by BruceRobertson** [stackci/node#1]
I really like the small size of the Alpine Linux based Node images, but I've run into an issue with the DNS resolver in Alpine Linux 3.3 not supporting DNS search domains in /etc/resolv.conf.

[Alpine Linux 3.4](https://alpinelinux.org/posts/Alpine-3.4.0-released.html) has been released which among other things does now support DNS search domains. 

Is there any chance that the stackci/node builds could be updated to use Alpine 3.4 as a base image?

**Comment by joshmanders** [comment]
Ah good to hear, @BruceRobertson I will see about updating previous images to use alphine 3.4, but I'll make a change to the docker image so that new builds will use it.
